import type { NextPage } from 'next'
import Head from 'next/head'
import Blog from '../components/children/blog'
import styles from '../styles/Home.module.scss'
import Images from '../components/children/image'
import About from '../components/children/About'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Jennifer{"'"}s Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.con}>
        <About />
        <Blog />
        <Images />
      </div>
    </div>
  )
}

export default Home
